### ISSUE TITLE
Non-ccsnoise liberty files contain ccsnoise data (for hs and ms libraries)

### ISSUE THREAD

**Issue by agorararmard** [google/skywater-pdk#77]
## Expected Behavior
sky130_fd_sc_hs__tt_025C_1v80.lib shouldn't contain ccsnoise related info. this is also the case for sky130_fd_sc_ms__tt_025C_1v80.lib

## Actual Behavior
sky130_fd_sc_hs__tt_025C_1v80.lib contains ccsnoise related info: i.e.
for inv_2:
`             ccsn_first_stage () {
                    dc_current ("ccsn_dc") {
                        index_1("-1.800000000, -0.900000000, -0.360000000, -0.180000000, 0.0000000000, 0.0900000000, 0.1800000000, 0.2700000000, 0.3600000000, 0.4500000000, 0.5400000000, 0.6300000000, 0.7200000000, 0.8100000000, 0.9000000000, 0.9900000000, 1.0800000000, 1.1700000000, 1.2600000000, 1.3500000000, 1.4400000000, 1.5300000000, 1.6200000000, 1.7100000000, 1.8000000000, 1.9800000000, 2.1600000000, 2.7000000000, 3.6000000000");
                        index_2("-1.800000000, -0.900000000, -0.360000000, -0.180000000, 0.0000000000, 0.0900000000, 0.1800000000, 0.2700000000, 0.3600000000, 0.4500000000, 0.5400000000, 0.6300000000, 0.7200000000, 0.8100000000, 0.9000000000, 0.9900000000, 1.0800000000, 1.1700000000, 1.2600000000, 1.3500000000, 1.4400000000, 1.5300000000, 1.6200000000, 1.7100000000, 1.8000000000, 1.9800000000, 2.1600000000, 2.7000000000, 3.6000000000");
                        values(                            "8.8354000000, 1.3865400000, 1.0756500000, 1.0189900000, 0.9559030000, 0.9219560000, 0.8864230000, 0.8493210000, 0.8106690000, 0.7704870000, 0.7287960000, 0.6856180000, 0.6409750000, 0.5948900000, 0.5473880000, 0.4984930000, 0.4482300000, 0.3966250000, 0.3437030000, 0.2894910000, 0.2340150000, 0.1773010000, 0.1193760000, 0.0602669000, -5.29305e-09, -0.119204000, -0.235303000, -0.646946000, -3.527050000", \
                            "8.5783400000, 1.1798400000, 0.9202040000, 0.8884130000, 0.8534060000, 0.8341080000, 0.8131440000, 0.7901050000, 0.7646560000, 0.7366030000, 0.7058640000, 0.6724120000, 0.6362450000, 0.5973740000, 0.5558190000, 0.5116040000, 0.4647600000, 0.4153180000, 0.3633170000, 0.3087960000, 0.2517990000, 0.1923720000, 0.1305620000, 0.0664210000, -2.20984e-08, -0.133245000, -0.264334000, -0.719539000, -3.547680000", \
                            "8.2941900000, 0.9276520000, 0.6915660000, 0.6703380000, 0.6480140000, 0.6362970000, 0.6240940000, 0.6112750000, 0.5976580000, 0.5829720000, 0.5668130000, 0.5486070000, 0.5276900000, 0.5035440000, 0.4759020000, 0.4446550000, 0.4097570000, 0.3711950000, 0.3289700000, 0.2830930000, 0.2335880000, 0.1804840000, 0.1238200000, 0.0636412000, -3.42017e-09, -0.131318000, -0.264331000, -0.731207000, -3.556270000", \
                            "8.1947800000, 0.8343000000, 0.5962890000, 0.5780840000, 0.5591240000, 0.5492730000, 0.5391060000, 0.5285510000, 0.5175070000, 0.5058300000, 0.4933050000, 0.4796040000, 0.4642060000, 0.4463770000, 0.4253640000, 0.4006920000, 0.3721480000, 0.3396440000, 0.3031380000, 0.2626130000, 0.2180670000, 0.1695070000, 0.1169550000, 0.0604394000, -3.37961e-09, -0.126859000, -0.257757000, -0.723358000, -3.555580000", \
                            "8.1048900000, 0.7688150000, 0.4955330000, 0.4800920000, 0.4641770000, 0.4559790000, 0.4475810000, 0.4389420000, 0.4300100000, 0.4207070000, 0.4109300000, 0.4005180000, 0.3892240000, 0.3766340000, 0.3620540000, 0.3445520000, 0.3233590000, 0.2980920000, 0.2685880000, 0.2347690000, 0.1965910000, 0.1540290000, 0.1070730000, 0.0557248000, -7.79901e-09, -0.119766000, -0.246572000, -0.707046000, -3.553310000", \
                            "8.0619800000, 0.7571000000, 0.4444100000, 0.4301240000, 0.4156160000, 0.4081730000, 0.4005740000, 0.3927890000, 0.3847790000, 0.3764910000, 0.3678500000, 0.3587490000, 0.3490230000, 0.3384040000, 0.3264190000, 0.3122530000, 0.2948810000, 0.2735710000, 0.2479910000, 0.2180000000, 0.1835210000, 0.1445040000, 0.1009200000, 0.0527529000, -4.02374e-08, -0.115120000, -0.239029000, -0.695213000, -3.551480000", \
                            "8.0195300000, 0.7592220000, 0.3941390000, 0.3802570000, 0.3670770000, 0.3603450000, 0.3534930000, 0.3465010000, 0.3393400000, 0.3319720000, 0.3243460000, 0.3163900000, 0.3079960000, 0.2989940000, 0.2890940000, 0.2777440000, 0.2639810000, 0.2467120000, 0.2252730000, 0.1993840000, 0.1689150000, 0.1337880000, 0.0939494000, 0.0493608000, -3.19743e-07, -0.109702000, -0.230097000, -0.680680000, -3.549140000", \
                            "7.9775400000, 0.7709770000, 0.3480860000, 0.3311490000, 0.3191790000, 0.3131150000, 0.3069640000, 0.3007080000, 0.2943290000, 0.2878010000, 0.2810890000, 0.2741430000, 0.2668960000, 0.2592410000, 0.2510030000, 0.2418650000, 0.2311710000, 0.2177860000, 0.2005970000, 0.1790280000, 0.1528440000, 0.1219210000, 0.0861783000, 0.0455523000, -2.68143e-06, -0.103504000, -0.219740000, -0.663290000, -3.546270000", \
                            "7.9364400000, 0.7878830000, 0.3147650000, 0.2836950000, 0.2725720000, 0.2671360000, 0.2616390000, 0.2560690000, 0.2504130000, 0.2446540000, 0.2387670000, 0.2327220000, 0.2264730000, 0.2199570000, 0.2130710000, 0.2056380000, 0.1973020000, 0.1872690000, 0.1742270000, 0.1571040000, 0.1354200000, 0.1089710000, 0.0776385000, 0.0413313000, -2.21030e-05, -0.096550400, -0.207969000, -0.642949000, -3.542930000", \
                            "7.8968900000, 0.8069130000, 0.3005910000, 0.2399950000, 0.2279210000, 0.2230570000, 0.2181710000, 0.2132380000, 0.2082500000, 0.2031930000, 0.1980540000, 0.1928130000, 0.1874410000, 0.1819000000, 0.1761310000, 0.1700370000, 0.1634410000, 0.1559350000, 0.1465430000, 0.1338040000, 0.1167430000, 0.0949711000, 0.0683061000, 0.0366253000, -0.000170862, -0.089002000, -0.194961000, -0.619808000, -3.539820000", \
                            "7.8596000000, 0.8267920000, 0.3002830000, 0.2062960000, 0.1858820000, 0.1814240000, 0.1770850000, 0.1727250000, 0.1683340000, 0.1639030000, 0.1594220000, 0.1548800000, 0.1502600000, 0.1455390000, 0.1406840000, 0.1356440000, 0.1303310000, 0.1245640000, 0.1178680000, 0.1090410000, 0.0965366000, 0.0795181000, 0.0576697000, 0.0308217000, -0.001155150, -0.081721500, -0.181707000, -0.595238000, -3.540550000", \
                            "7.8252600000, 0.8474990000, 0.3066080000, 0.1889820000, 0.1470810000, 0.1421300000, 0.1381130000, 0.1341470000, 0.1301780000, 0.1261920000, 0.1221780000, 0.1181300000, 0.1140360000, 0.1098830000, 0.1056540000, 0.1013220000, 0.0968430000, 0.0921410000, 0.0870339000, 0.0809529000, 0.0724460000, 0.0599642000, 0.0428284000, 0.0207766000, -0.006356470, -0.078536300, -0.172456000, -0.574884000, -3.556480000", \
                            "7.7944700000, 0.8696340000, 0.3166740000, 0.1825880000, 0.1120880000, 0.1024810000, 0.0974312000, 0.0931689000, 0.0890564000, 0.0849910000, 0.0809377000, 0.0768789000, 0.0728029000, 0.0686991000, 0.0645563000, 0.0603603000, 0.0560910000, 0.0517154000, 0.0471685000, 0.0422686000, 0.0363280000, 0.0276462000, 0.0147674000, -0.002835470, -0.025386400, -0.089542300, -0.177694000, -0.570116000, -3.601660000", \
                            "7.7677000000, 0.8939660000, 0.3299980000, 0.1803370000, 0.0813966000, 0.0596518000, 0.0480692000, 0.0413877000, 0.0360008000, 0.0310545000, 0.0263157000, 0.0216926000, 0.0171397000, 0.0126308000, 0.0081479200, 0.0036770500, -0.000795384, -0.005285580, -0.009818280, -0.014446000, -0.019348700, -0.025357000, -0.034384700, -0.047704500, -0.065708100, -0.121594000, -0.203525000, -0.584131000, -3.671170000", \
                            "7.7453300000, 0.9211730000, 0.3465950000, 0.1807340000, 0.0554120000, 0.0180132000, -0.005982570, -0.019189000, -0.027409200, -0.033929700, -0.039707000, -0.045077100, -0.050190400, -0.055125900, -0.059930000, -0.064632700, -0.069255100, -0.073813800, -0.078324500, -0.082806800, -0.087301800, -0.091985400, -0.097856000, -0.106959000, -0.120291000, -0.167160000, -0.241873000, -0.607079000, -3.749370000", \
                            "7.7275800000, 0.9517520000, 0.3663800000, 0.1841040000, 0.0344464000, -0.018160800, -0.055779400, -0.078961300, -0.091878200, -0.100657000, -0.107737000, -0.113941000, -0.119615000, -0.124930000, -0.129982000, -0.134831000, -0.139517000, -0.144067000, -0.148500000, -0.152834000, -0.157085000, -0.161286000, -0.165613000, -0.171289000, -0.180286000, -0.217784000, -0.284568000, -0.631581000, -3.828450000", \
                            "7.7145800000, 0.9859950000, 0.3891300000, 0.1908530000, 0.0187246000, -0.047718600, -0.098327500, -0.132803000, -0.152242000, -0.164038000, -0.172733000, -0.179913000, -0.186213000, -0.191936000, -0.197250000, -0.202255000, -0.207016000, -0.211577000, -0.215972000, -0.220223000, -0.224352000, -0.228376000, -0.232325000, -0.236435000, -0.242251000, -0.270540000, -0.328937000, -0.655874000, -3.906730000", \
                            "7.7063500000, 1.0240200000, 0.4145400000, 0.2011460000, 0.0083252600, -0.070699800, -0.133461000, -0.179410000, -0.206954000, -0.222662000, -0.233379000, -0.241762000, -0.248844000, -0.255106000, -0.260802000, -0.266086000, -0.271055000, -0.275775000, -0.280295000, -0.284648000, -0.288863000, -0.292961000, -0.296964000, -0.300910000, -0.305353000, -0.325255000, -0.374821000, -0.680504000, -3.984170000", \
                            "7.7028300000, 1.0657600000, 0.4421090000, 0.2146960000, 0.0028328300, -0.087755000, -0.161944000, -0.219171000, -0.256125000, -0.276878000, -0.290209000, -0.300175000, -0.308338000, -0.315399000, -0.321726000, -0.327531000, -0.332946000, -0.338061000, -0.342937000, -0.347622000, -0.352148000, -0.356542000, -0.360826000, -0.365022000, -0.369297000, -0.382922000, -0.422924000, -0.706555000, -4.060820000", \
                            "7.7038800000, 1.1106600000, 0.4706320000, 0.2302400000, 0.0007694700, -0.100542000, -0.185539000, -0.253723000, -0.301026000, -0.328138000, -0.344816000, -0.356812000, -0.366379000, -0.374504000, -0.381684000, -0.388203000, -0.394236000, -0.399898000, -0.405268000, -0.410404000, -0.415346000, -0.420129000, -0.424778000, -0.429317000, -0.433807000, -0.444352000, -0.474252000, -0.734956000, -4.136620000", \
                            "7.7090100000, 1.1572100000, 0.4981400000, 0.2458230000, 0.0001999110, -0.110982000, -0.206092000, -0.284711000, -0.342752000, -0.377506000, -0.398278000, -0.412698000, -0.423911000, -0.433261000, -0.441415000, -0.448741000, -0.455465000, -0.461733000, -0.467644000, -0.473269000, -0.478660000, -0.483857000, -0.488892000, -0.493791000, -0.498591000, -0.508440000, -0.529417000, -0.766292000, -4.211370000", \
                            "7.7169400000, 1.2034300000, 0.5231900000, 0.2601970000, 5.460760e-05, -0.120056000, -0.224461000, -0.312816000, -0.381465000, -0.425008000, -0.450691000, -0.467934000, -0.481004000, -0.491708000, -0.500918000, -0.509110000, -0.516566000, -0.523470000, -0.529944000, -0.536076000, -0.541928000, -0.547549000, -0.552976000, -0.558241000, -0.563376000, -0.573492000, -0.588463000, -0.800850000, -4.284870000", \
                            "7.7259700000, 1.2480800000, 0.5453420000, 0.2729940000, 1.518310e-05, -0.128059000, -0.240893000, -0.338202000, -0.416956000, -0.470196000, -0.501739000, -0.522276000, -0.537445000, -0.549641000, -0.559993000, -0.569106000, -0.577334000, -0.584902000, -0.591960000, -0.598612000, -0.604936000, -0.610989000, -0.616815000, -0.622450000, -0.627927000, -0.638575000, -0.650742000, -0.838711000, -4.356940000", \
                            "7.7350800000, 1.2906300000, 0.5646110000, 0.2841880000, 3.991870e-06, -0.135090000, -0.255482000, -0.360933000, -0.449055000, -0.512511000, -0.550996000, -0.575413000, -0.592976000, -0.606827000, -0.618422000, -0.628522000, -0.637566000, -0.645830000, -0.653495000, -0.660686000, -0.667494000, -0.673988000, -0.680219000, -0.686229000, -0.692055000, -0.703307000, -0.714800000, -0.879801000, -4.427450000", \
                            "7.7439500000, 1.3307200000, 0.5811480000, 0.2938450000, 8.779440e-07, -0.141213000, -0.268310000, -0.381083000, -0.477718000, -0.551426000, -0.597990000, -0.627016000, -0.647341000, -0.663048000, -0.676006000, -0.687171000, -0.697086000, -0.706084000, -0.714383000, -0.722134000, -0.729443000, -0.736391000, -0.743037000, -0.749429000, -0.755610000, -0.767491000, -0.779184000, -0.923938000, -4.496260000", \
                            "7.7605900000, 1.4021900000, 0.6068060000, 0.3089500000, 2.409170e-08, -0.150970000, -0.289061000, -0.414107000, -0.525105000, -0.617605000, -0.683147000, -0.724216000, -0.751569000, -0.771796000, -0.787955000, -0.801553000, -0.813413000, -0.824026000, -0.833702000, -0.842654000, -0.851028000, -0.858932000, -0.866448000, -0.873638000, -0.880553000, -0.893743000, -0.906427000, -1.020260000, -4.628540000", \
                            "7.7755000000, 1.4593500000, 0.6239590000, 0.3191890000, 1.325160e-08, -0.157828000, -0.304014000, -0.438415000, -0.560475000, -0.667822000, -0.753177000, -0.810718000, -0.848013000, -0.874329000, -0.894585000, -0.911173000, -0.925349000, -0.937836000, -0.949081000, -0.959378000, -0.968929000, -0.977879000, -0.986337000, -0.994383000, -1.002080000, -1.016660000, -1.030500000, -1.125150000, -4.753460000", \
                            "7.8056300000, 1.5247200000, 0.6393900000, 0.3291780000, 4.678120e-08, -0.165897000, -0.323351000, -0.472251000, -0.612446000, -0.743620000, -0.864838000, -0.973086000, -1.061320000, -1.124760000, -1.168870000, -1.201280000, -1.226700000, -1.247690000, -1.265670000, -1.281490000, -1.295710000, -1.308690000, -1.320690000, -1.331890000, -1.342430000, -1.361940000, -1.379880000, -1.462980000, -5.085640000", \
                            "7.7960700000, 1.4512700000, 0.6064390000, 0.3121720000, 2.075150e-07, -0.158746000, -0.312372000, -0.460813000, -0.604008000, -0.741893000, -0.874401000, -1.001440000, -1.122840000, -1.238240000, -1.346710000, -1.445880000, -1.531150000, -1.598840000, -1.650620000, -1.690980000, -1.723660000, -1.751090000, -1.774800000, -1.795750000, -1.814590000, -1.847650000, -1.876300000, -1.978290000, -5.532440000");
                    }
                    is_inverting : "true";
                    is_needed : "true";
                    miller_cap_fall : 0.0013930000;
                    miller_cap_rise : 0.0010600000;
                    output_voltage_fall () {
                        vector ("ccsn_ovrf") {
                            index_1("0.0100000000");
                            index_2("0.0125935000");
                            index_3("0.0159462700, 0.0231825100, 0.0307311800, 0.0390792500, 0.0513429300");
                            values("1.6200000000, 1.2600000000, 0.9000000000, 0.5400000000, 0.1800000000");
                        }
                        vector ("ccsn_ovrf") {
                            index_1("0.0100000000");
                            index_2("0.0377805000");
                            index_3("0.0221444200, 0.0418173800, 0.0623751300, 0.0848906000, 0.1178906000");
                            values("1.6200000000, 1.2600000000, 0.9000000000, 0.5400000000, 0.1800000000");
                        }
                        vector ("ccsn_ovrf") {
                            index_1("0.1000000000");
                            index_2("0.0125935000");
                            index_3("0.0680732500, 0.0820050500, 0.0923445600, 0.1015619000, 0.1138112000");
                            values("1.6200000000, 1.2600000000, 0.9000000000, 0.5400000000, 0.1800000000");
                        }
                        vector ("ccsn_ovrf") {
                            index_1("0.1000000000");
                            index_2("0.0377805000");
                            index_3("0.0807543000, 0.1045338000, 0.1251596000, 0.1476136000, 0.1805000000");
                            values("1.6200000000, 1.2600000000, 0.9000000000, 0.5400000000, 0.1800000000");
                        }
                    }
                    output_voltage_rise () {
                        vector ("ccsn_ovrf") {
                            index_1("0.0100000000");
                            index_2("0.00773628333333333");
                            index_3("0.0181217400, 0.0261361800, 0.0351026100, 0.0461963500, 0.0672911800");
                            values("0.1800000000, 0.5400000000, 0.9000000000, 1.2600000000, 1.6200000000");
                        }
                        vector ("ccsn_ovrf") {
                            index_1("0.0100000000");
                            index_2("0.0232088500");
                            index_3("0.0248125600, 0.0458322800, 0.0691287600, 0.0979249100, 0.1495268000");
                            values("0.1800000000, 0.5400000000, 0.9000000000, 1.2600000000, 1.6200000000");
                        }
                        vector ("ccsn_ovrf") {
                            index_1("0.1000000000");
                            index_2("0.00773628333333333");
                            index_3("0.0729969300, 0.0886069900, 0.0999978800, 0.1112065000, 0.1323333000");
                            values("0.1800000000, 0.5400000000, 0.9000000000, 1.2600000000, 1.6200000000");
                        }
                        vector ("ccsn_ovrf") {
                            index_1("0.1000000000");
                            index_2("0.0232088500");
                            index_3("0.0862495200, 0.1105457000, 0.1338412000, 0.1625015000, 0.2142057000");
                            values("0.1800000000, 0.5400000000, 0.9000000000, 1.2600000000, 1.6200000000");
                        }
                    }
                    propagated_noise_high () {
                        vector ("ccsn_pnlh") {
                            index_1("0.94658203125");
                            index_2("0.817547469256417");
                            index_3("0.0125935000");
                            index_4("0.4014175000, 0.4281398000, 0.4769807000, 0.5272619000, 0.5665166000");
                            values("1.4715992500, 1.2745588000, 1.1431985000, 1.2745588000, 1.4715992500");
                        }
                        vector ("ccsn_pnlh") {
                            index_1("1.11181640625");
                            index_2("0.361727496031487");
                            index_3("0.0125935000");
                            index_4("0.1808946000, 0.1994527000, 0.2300182000, 0.2717831000, 0.3013945000");
                            values("1.3568981000, 1.0910369600, 0.9137962000, 1.0910369600, 1.3568981000");
                        }
                        vector ("ccsn_pnlh") {
                            index_1("1.27177734375");
                            index_2("0.21399286316168");
                            index_3("0.0125935000");
                            index_4("0.1091310000, 0.1234631000, 0.1476893000, 0.1794429000, 0.2024574000");
                            values("1.3140491500, 1.0224786400, 0.8280983000, 1.0224786400, 1.3140491500");
                        }
                        vector ("ccsn_pnlh") {
                            index_1("0.94658203125");
                            index_2("0.408773734628208");
                            index_3("0.0125935000");
                            index_4("0.2044639000, 0.2185944000, 0.2481555000, 0.2759360000, 0.3047003000");
                            values("1.6183499500, 1.5093599200, 1.4366999000, 1.5093599200, 1.6183499500");
                        }
                        vector ("ccsn_pnlh") {
                            index_1("1.27177734375");
                            index_2("0.10699643158084");
                            index_3("0.0125935000");
                            index_4("0.0577082700, 0.0649759300, 0.0789561800, 0.0970957900, 0.1142373000");
                            values("1.5637841500, 1.4220546400, 1.3275683000, 1.4220546400, 1.5637841500");
                        }
                        vector ("ccsn_pnlh") {
                            index_1("1.11181640625");
                            index_2("0.361727496031487");
                            index_3("0.0377805000");
                            index_4("0.1830511000, 0.2032471000, 0.2394775000, 0.2891633000, 0.3390302000");
                            values("1.6205664000, 1.5129062400, 1.4411328000, 1.5129062400, 1.6205664000");
                        }
                        vector ("ccsn_pnlh") {
                            index_1("1.27177734375");
                            index_2("0.21399286316168");
                            index_3("0.0377805000");
                            index_4("0.1106969000, 0.1258065000, 0.1507812000, 0.1937964000, 0.2327066000");
                            values("1.6115585500, 1.4984936800, 1.4231171000, 1.4984936800, 1.6115585500");
                        }
                    }
                    propagated_noise_low () {
                        vector ("ccsn_pnlh") {
                            index_1("1.02392578125");
                            index_2("0.751278788561192");
                            index_3("0.00773628333333333");
                            index_4("0.3655855000, 0.3845582000, 0.4074894000, 0.4390772000, 0.4590068000");
                            values("0.1785870000, 0.2857392000, 0.3571740000, 0.2857392000, 0.1785870000");
                        }
                        vector ("ccsn_pnlh") {
                            index_1("1.20498046875");
                            index_2("0.384242931568557");
                            index_3("0.00773628333333333");
                            index_4("0.1904791000, 0.2072896000, 0.2307878000, 0.2585638000, 0.2744365000");
                            values("0.3779771500, 0.6047634400, 0.7559543000, 0.6047634400, 0.3779771500");
                        }
                        vector ("ccsn_pnlh") {
                            index_1("1.35791015625");
                            index_2("0.248276892662061");
                            index_3("0.00773628333333333");
                            index_4("0.1251608000, 0.1396501000, 0.1624393000, 0.1830177000, 0.1961566000");
                            values("0.4577327000, 0.7323723200, 0.9154654000, 0.7323723200, 0.4577327000");
                        }
                        vector ("ccsn_pnlh") {
                            index_1("1.02392578125");
                            index_2("0.375639394280596");
                            index_3("0.00773628333333333");
                            index_4("0.1845324000, 0.1953740000, 0.2113431000, 0.2283755000, 0.2428232000");
                            values("0.1123415500, 0.1797464800, 0.2246831000, 0.1797464800, 0.1123415500");
                        }
                        vector ("ccsn_pnlh") {
                            index_1("1.35791015625");
                            index_2("0.124138446331031");
                            index_3("0.00773628333333333");
                            index_4("0.0657779300, 0.0730955600, 0.0844812000, 0.0953494600, 0.1034069000");
                            values("0.2421872000, 0.3874995200, 0.4843744000, 0.3874995200, 0.2421872000");
                        }
                        vector ("ccsn_pnlh") {
                            index_1("1.20498046875");
                            index_2("0.384242931568557");
                            index_3("0.0232088500");
                            index_4("0.1916096000, 0.2101976000, 0.2369963000, 0.2676142000, 0.2889050000");
                            values("0.1693214500, 0.2709143200, 0.3386429000, 0.2709143200, 0.1693214500");
                        }
                        vector ("ccsn_pnlh") {
                            index_1("1.35791015625");
                            index_2("0.248276892662061");
                            index_3("0.0232088500");
                            index_4("0.1265402000, 0.1420239000, 0.1653819000, 0.1890249000, 0.2064404000");
                            values("0.1966904000, 0.3147046400, 0.3933808000, 0.3147046400, 0.1966904000");
                        }
                    }
                    stage_type : "both";
                }`

## Steps to Reproduce the Problem

1. run make sky130_fd_sc_hs
2. check the timing folder under v0.0.2
3. You'll find that both sky130_fd_sc_hs__tt_025C_1v80.lib and sky130_fd_sc_hs__tt_025C_1v80_ccsnoise.lib contain the ccsnoise information.

This is also the case for the ms library

## Specifications

- Version: v0.0.2

**Comment by mithro** [comment]
@agorararmard This should be fixed now.

**Comment by agorararmard** [comment]
@mithro  I just pulled and did git submodule update --init and ran make sky130_fd_sc_hs. I found that the issue still exists in all three versions (latest, v0.0.1, v0.0.2). so to reiterate on what's the problem:

1- we have one json description for the typical hs library with 25C and 1.80V: sky130_fd_sc_hs__tt_025C_1v80_ccsnoise.lib.json
2- However, two liberties are generated: sky130_fd_sc_hs__tt_025C_1v80_ccsnoise.lib and sky130_fd_sc_hs__tt_025C_1v80.lib.
3- We at efabless, openLane team, are only interested in this one sky130_fd_sc_hs__tt_025C_1v80.lib
4- Because yosys+ABC doesn't know how to parse ccsnoise information from liberty, and that's why we expect the file that doesn't contain the _ccsnoise postfix not to contain any ccsnoice information. Thus, the flow fails at synthesis.

I can share with you a small design so you can run against yosys and validate it from your side.

**Comment by mithro** [comment]
A number of other people have successfully use these `.lib` files with Yosys, so it is unclear to me what is going on.

Can you please explain both;
 * How the `sky130_fd_sc_hs__tt_025C_1v80.lib` files has ccsnoise in it? 
 * The error you are getting from Yosys?

**Comment by agorararmard** [comment]
For any given cell in sky130_fd_sc_hs__tt_025C_1v80.lib there exists a timing section under which there exists: `ccsn_first_stage () ` as a sub section. this subsection shouldn't exist since sky130_fd_sc_hs__tt_025C_1v80 doesn't have the _ccsnoise postfix. The whole subsection is listed above. Also any other ccsn related subsection. 

As for the yosys crash, we're still investigating the root cause of this. However, it worked fine with the hd library and it doesn't have the same issue (the cssn subsections).

**Comment by mithro** [comment]
It sounds like you are using an old version of the PDK? I just checked `sky130_fd_sc_hs__tt_025C_1v80.lib` and could find no `ccsn_first_stage ()` in the file?

**Comment by mithro** [comment]
Please make sure you have https://github.com/google/skywater-pdk/pull/92 in your repo.

**Comment by agorararmard** [comment]
@mithro 
this is my git log from a fresh clone
```
commit ad3b507e384ac364472571bcb1bc4e02fd649ad6 (HEAD -> master, origin/master, origin/HEAD)
Merge: f2838cf b626ca0
Author: Tim Ansell <me@mith.ro>
Date:   Sun Jul 12 22:59:42 2020 -0700

    Merge pull request #92 from mithro/ccsnoise-fix
    
    Fix ccsnoise properties ending up in basic liberty files.
```
steps done:
 1. git submodule update --init libraries/sky130_fd_sc_hs/latest
 2. make sky130_fd_sc_hs 
 3. I opened sky130_fd_sc_hs/latest/timing/sky130_fd_sc_hs__tt_025C_1v80.lib
 4. under sky130_fd_sc_hs__buf_1: timing(){ I find ccsn_first_stage ()

Is there anything I'm doing wrong in these steps?

**Comment by mithro** [comment]
I can confirm that I am seeing this. It seems I removed the ccsnoise from pins but reverted the removal in the timing section.

**Comment by mithro** [comment]
Actually, now I'm not seeing it...

**Comment by msaligane** [comment]
I did a quick check in primetime of `sky130_fd_sc_hs`

I see sky130_fd_sc_hs__tt_025C_1v80.lib has these issues from primetime:
```
Error: Line 13353, Cell 'sky130_fd_sc_hs__a21bo_1', pin 'B1_N', The 'ccsn_dc' refers to a nonexistent or empty 'lu_table_template'. (LBDB-259)
Error: Line 13391, Cell 'sky130_fd_sc_hs__a21bo_1', pin 'B1_N', The 'ccsn_ovrf' refers to a nonexistent or empty 'lu_table_template'. (LBDB-259)
Error: Line 13397, Cell 'sky130_fd_sc_hs__a21bo_1', pin 'B1_N', The 'ccsn_ovrf' refers to a nonexistent or empty 'lu_table_template'. (LBDB-259)
Error: Line 13405, Cell 'sky130_fd_sc_hs__a21bo_1', pin 'B1_N', The 'ccsn_ovrf' refers to a nonexistent or empty 'lu_table_template'. (LBDB-259)
```

But other hs libs, like sky130_fd_sc_hs__tt_025C_1v89.lib and sky130_fd_sc_hs__tt_025C_2v10.lib, they have passed my tests with no errors.

**Comment by msaligane** [comment]
For example if you look at a21bo cell in hs lib, there is no sky130_fd_sc_hs__a21bo_1__tt_025C_1v80.lib.json
see below:
```
sky130_fd_sc_hs__a21bo_1__tt_025C_1v20.lib.json
sky130_fd_sc_hs__a21bo_1__tt_025C_1v35.lib.json
sky130_fd_sc_hs__a21bo_1__tt_025C_1v44.lib.json
sky130_fd_sc_hs__a21bo_1__tt_025C_1v50.lib.json
sky130_fd_sc_hs__a21bo_1__tt_025C_1v62.lib.json
sky130_fd_sc_hs__a21bo_1__tt_025C_1v68.lib.json
**sky130_fd_sc_hs__a21bo_1__tt_025C_1v80_ccsnoise.lib.json**
sky130_fd_sc_hs__a21bo_1__tt_025C_1v89.lib.json
sky130_fd_sc_hs__a21bo_1__tt_025C_2v10.lib.json
sky130_fd_sc_hs__a21bo_1__tt_100C_1v80.lib.json
sky130_fd_sc_hs__a21bo_1__tt_150C_1v80.lib.json
```

**Comment by mithro** [comment]
I have replicated the error and a fix should be in #102.
